SET ROLE newsfeed_owner;

-- Table access is intentionally absent. SECURITY DEFINER routines are the only
-- database capability granted to the runtime role.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM newsfeed_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM newsfeed_app;

REVOKE ALL ON SCHEMA pkg_users, pkg_posts, pkg_feed, pkg_outbox, pkg_lab_seed FROM PUBLIC;
REVOKE ALL ON ALL ROUTINES IN SCHEMA pkg_users FROM PUBLIC;
REVOKE ALL ON ALL ROUTINES IN SCHEMA pkg_posts FROM PUBLIC;
REVOKE ALL ON ALL ROUTINES IN SCHEMA pkg_feed FROM PUBLIC;
REVOKE ALL ON ALL ROUTINES IN SCHEMA pkg_outbox FROM PUBLIC;
REVOKE ALL ON ALL ROUTINES IN SCHEMA pkg_lab_seed FROM PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE newsfeed_owner IN SCHEMA pkg_users
  REVOKE EXECUTE ON ROUTINES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE newsfeed_owner IN SCHEMA pkg_posts
  REVOKE EXECUTE ON ROUTINES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE newsfeed_owner IN SCHEMA pkg_feed
  REVOKE EXECUTE ON ROUTINES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE newsfeed_owner IN SCHEMA pkg_outbox
  REVOKE EXECUTE ON ROUTINES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE newsfeed_owner IN SCHEMA pkg_lab_seed
  REVOKE EXECUTE ON ROUTINES FROM PUBLIC;

GRANT USAGE ON SCHEMA pkg_users, pkg_posts, pkg_feed, pkg_outbox, pkg_lab_seed
  TO newsfeed_app;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA pkg_users TO newsfeed_app;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA pkg_posts TO newsfeed_app;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA pkg_feed TO newsfeed_app;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA pkg_outbox TO newsfeed_app;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA pkg_lab_seed TO newsfeed_app;

RESET ROLE;
